In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/ultimate-spotify-tracks-db/SpotifyFeatures.csv

In [2]:
df=pd.read_csv('/kaggle/input/ultimate-spotify-tracks-db/SpotifyFeatures.csv')

In [3]:
df

,genre,artist_name,track_name,track_id,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence
0,Movie,Henri Salvador,C'est beau de faire un Show,0BRjO6ga9RKCKjfDqeFgWV,0,0.61100,0.389,99373,0.910,0.000000,C#,0.3460,-1.828,Major,0.0525,166.969,4/4,0.814
1,Movie,Martin & les fées,Perdu d'avance (par Gad Elmaleh),0BjC1NfoEOOusryehmNudP,1,0.24600,0.590,137373,0.737,0.000000,F#,0.1510,-5.559,Minor,0.0868,174.003,4/4,0.816
2,Movie,Joseph Williams,Don't Let Me Be Lonely Tonight,0CoSDzoNIKCRs124s9uTVy,3,0.95200,0.663,170267,0.131,0.000000,C,0.1030,-13.879,Minor,0.0362,99.488,5/4,0.368
3,Movie,Henri Salvador,Dis-moi Monsieur Gordon Cooper,0Gc6TVm52BwZD07Ki6tIvf,0,0.70300,0.240,152427,0.326,0.000000,C#,0.0985,-12.178,Major,0.0395,171.758,4/4,0.227
4,Movie,Fabien Nataf,Ouverture,0IuslXpMROHdEPvSl1fTQK,4,0.95000,0.331,82625,0.225,0.123000,F,0.2020,-21.150,Major,0.0456,140.576,4/4,0.390
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232720,Soul,Slave,Son Of Slide,2XGLdVl7lGeq8ksM6Al7jT,39,0.00384,0.687,326240,0.714,0.544000,D,0.0845,-10.626,Major,0.0316,115.542,4/4,0.962
232721,Soul,Jr Thomas & The Volcanos,Burning Fire,1qWZdkBl4UVPj9lK6HuuFM,38,0.03290,0.785,282447,0.683,0.000880,E,0.2370,-6.944,Minor,0.0337,113.830,4/4,0.969
232722,Soul,Muddy Waters,(I'm Your) Hoochie Coochie Man,2ziWXUmQLrXTiYjCg2fZ2t,47,0.90100,0.517,166960,0.419,0.000000,D,0.0945,-8.282,Major,0.1480,84.135,4/4,0.813
232723,Soul,R.LUM.R,With My Words,6EFsue2YbIG4Qkq8Zr9Rir,44,0.26200,0.745,222442,0.704,0.000000,A,0.3330,-7.137,Major,0.1460,100.031,4/4,0.489
232724,Soul,Mint Condition,You Don't Have To Hurt No More,34XO9RwPMKjbvRry54QzWn,35,0.09730,0.758,323027,0.470,0.000049,G#,0.0836,-6.708,Minor,0.0287,113.897,4/4,0.479

In [4]:
df.tail()

,genre,artist_name,track_name,track_id,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence
232720,Soul,Slave,Son Of Slide,2XGLdVl7lGeq8ksM6Al7jT,39,0.00384,0.687,326240,0.714,0.544000,D,0.0845,-10.626,Major,0.0316,115.542,4/4,0.962
232721,Soul,Jr Thomas & The Volcanos,Burning Fire,1qWZdkBl4UVPj9lK6HuuFM,38,0.03290,0.785,282447,0.683,0.000880,E,0.2370,-6.944,Minor,0.0337,113.830,4/4,0.969
232722,Soul,Muddy Waters,(I'm Your) Hoochie Coochie Man,2ziWXUmQLrXTiYjCg2fZ2t,47,0.90100,0.517,166960,0.419,0.000000,D,0.0945,-8.282,Major,0.1480,84.135,4/4,0.813
232723,Soul,R.LUM.R,With My Words,6EFsue2YbIG4Qkq8Zr9Rir,44,0.26200,0.745,222442,0.704,0.000000,A,0.3330,-7.137,Major,0.1460,100.031,4/4,0.489
232724,Soul,Mint Condition,You Don't Have To Hurt No More,34XO9RwPMKjbvRry54QzWn,35,0.09730,0.758,323027,0.470,0.000049,G#,0.0836,-6.708,Minor,0.0287,113.897,4/4,0.479

In [5]:
df.head()

,genre,artist_name,track_name,track_id,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence
0,Movie,Henri Salvador,C'est beau de faire un Show,0BRjO6ga9RKCKjfDqeFgWV,0,0.611,0.389,99373,0.910,0.000,C#,0.3460,-1.828,Major,0.0525,166.969,4/4,0.814
1,Movie,Martin & les fées,Perdu d'avance (par Gad Elmaleh),0BjC1NfoEOOusryehmNudP,1,0.246,0.590,137373,0.737,0.000,F#,0.1510,-5.559,Minor,0.0868,174.003,4/4,0.816
2,Movie,Joseph Williams,Don't Let Me Be Lonely Tonight,0CoSDzoNIKCRs124s9uTVy,3,0.952,0.663,170267,0.131,0.000,C,0.1030,-13.879,Minor,0.0362,99.488,5/4,0.368
3,Movie,Henri Salvador,Dis-moi Monsieur Gordon Cooper,0Gc6TVm52BwZD07Ki6tIvf,0,0.703,0.240,152427,0.326,0.000,C#,0.0985,-12.178,Major,0.0395,171.758,4/4,0.227
4,Movie,Fabien Nataf,Ouverture,0IuslXpMROHdEPvSl1fTQK,4,0.950,0.331,82625,0.225,0.123,F,0.2020,-21.150,Major,0.0456,140.576,4/4,0.390

In [6]:
df.dtypes

genre                object
artist_name          object
track_name           object
track_id             object
popularity            int64
acousticness        float64
danceability        float64
duration_ms           int64
energy              float64
instrumentalness    float64
key                  object
liveness            float64
loudness            float64
mode                 object
speechiness         float64
tempo               float64
time_signature       object
valence             float64
dtype: object

In [7]:
df.shape

(232725, 18)

In [8]:
pd.isnull(df).sum()

genre               0
artist_name         0
track_name          0
track_id            0
popularity          0
acousticness        0
danceability        0
duration_ms         0
energy              0
instrumentalness    0
key                 0
liveness            0
loudness            0
mode                0
speechiness         0
tempo               0
time_signature      0
valence             0
dtype: int64

In [9]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
popularity,232725.0,41.127502,18.189948,0.00000,29.0000,43.000000,55.0000,100.000
acousticness,232725.0,0.368560,0.354768,0.00000,0.0376,0.232000,0.7220,0.996
danceability,232725.0,0.554364,0.185608,0.05690,0.4350,0.571000,0.6920,0.989
duration_ms,232725.0,235122.339306,118935.909299,15387.00000,182857.0000,220427.000000,265768.0000,5552917.000
energy,232725.0,0.570958,0.263456,0.00002,0.3850,0.605000,0.7870,0.999
instrumentalness,232725.0,0.148301,0.302768,0.00000,0.0000,0.000044,0.0358,0.999
liveness,232725.0,0.215009,0.198273,0.00967,0.0974,0.128000,0.2640,1.000
loudness,232725.0,-9.569885,5.998204,-52.45700,-11.7710,-7.762000,-5.5010,3.744
speechiness,232725.0,0.120765,0.185518,0.02220,0.0367,0.050100,0.1050,0.967
tempo,232725.0,117.666585,30.898907,30.37900,92.9590,115.778000,139.0540,242.903
valence,232725.0,0.454917,0.260065,0.00000,0.2370,0.444000,0.6600,1.000

In [10]:

sorted_df=df.sort_values('tempo',ascending=True).head(10)
sorted_df

,genre,artist_name,track_name,track_id,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,time_signature,valence
203679,Soundtrack,Tomoki Miyoshi,Voices of Winter,6rf8veOzvXinbAfuBlOKMB,29,0.970,0.2250,77333,0.03470,0.944000,B,0.1130,-27.025,Major,0.0370,30.379,3/4,0.0356
206109,Soundtrack,Thomas Newman,The Question,6Fn0mPbXN0rP0MXP3HHqUl,24,0.603,0.0666,85573,0.00549,0.879000,F,0.1450,-41.624,Minor,0.0429,31.033,3/4,0.0605
199721,Soundtrack,Alberto Iglesias,Lucía,1Bq0ca1doheGTHw83KBwPW,42,0.959,0.3120,116693,0.09310,0.867000,D,0.1150,-23.102,Major,0.0354,31.689,4/4,0.1520
201598,Soundtrack,Ennio Morricone,"Love Theme (From ""Cinema Paradiso"")",7BHX4FX2hfw14gnvcQVJPO,37,0.927,0.1890,197307,0.16000,0.421000,A#,0.1110,-19.862,Major,0.0427,31.988,4/4,0.0749
34715,Anime,Yuka,テルーの唄(ゲド戦記より),4zv7jl7u6kwM2lhmxdv25k,22,0.978,0.3790,215307,0.04970,0.268000,D,0.0667,-19.111,Major,0.0392,32.080,4/4,0.1590
54,Movie,Jean Piat,L'Âne chargé d'éponges et l'Âne chargé de sel,2BF5SlaZRL0sYUDBgwjmbo,0,0.924,0.6830,101653,0.14700,0.000000,G#,0.6060,-21.998,Major,0.8220,32.244,4/4,0.5950
168261,Comedy,Brian Regan,Spider Webs & Bees,3UI8Ig1tf7QmAGYLpOaI6f,33,0.833,0.6260,57333,0.62400,0.000009,F,0.9090,-14.043,Major,0.8200,32.451,4/4,0.2840
195413,Movie,Charlton Heston,In the Beginning,2K6wtWjangaL3FyDGdNxie,0,0.947,0.7430,50879,0.01110,0.000199,B,0.1300,-29.909,Major,0.2790,32.509,3/4,0.4360
221510,World,Eluvium,is to create,1qIHS0F12Vrp0H6IJspaL3,25,0.869,0.2200,32000,0.10200,0.965000,F,0.1030,-22.205,Major,0.0430,33.593,3/4,0.0337
72247,Children's Music,Tom's Music Box,"Trio for Horn, Violin and Piano in Eb, Op. 40; I",06W6KjnlxohJDxDFoXwfpY,20,0.584,0.6910,47368,0.23900,0.907000,D#,0.1060,-8.024,Major,0.0701,33.792,4/4,0.3490

In [11]:
df[["track_name"]].iloc[18]

track_name    Veunise
Name: 18, dtype: object

In [12]:
df['popularity'].isnull()

0         False
1         False
2         False
3         False
4         False
          ...
232720    False
232721    False
232722    False
232723    False
232724    False
Name: popularity, Length: 232725, dtype: bool

In [13]:
df.info

<bound method DataFrame.info of         genre               artist_name                        track_name  \
0       Movie            Henri Salvador       C'est beau de faire un Show
1       Movie         Martin & les fées  Perdu d'avance (par Gad Elmaleh)
2       Movie           Joseph Williams    Don't Let Me Be Lonely Tonight
3       Movie            Henri Salvador    Dis-moi Monsieur Gordon Cooper
4       Movie              Fabien Nataf                         Ouverture
...       ...                       ...                               ...
232720   Soul                     Slave                      Son Of Slide
232721   Soul  Jr Thomas & The Volcanos                      Burning Fire
232722   Soul              Muddy Waters    (I'm Your) Hoochie Coochie Man
232723   Soul                   R.LUM.R                     With My Words
232724   Soul            Mint Condition    You Don't Have To Hurt No More

                      track_id  popularity  acousticness  danceability  \
0       0BRjO6ga9RKCKjfDqeFgWV           0       0.61100         0.389
1       0BjC1NfoEOOusryehmNudP           1       0.24600         0.590
2       0CoSDzoNIKCRs124s9uTVy           3       0.95200         0.663
3       0Gc6TVm52BwZD07Ki6tIvf           0       0.70300         0.240
4       0IuslXpMROHdEPvSl1fTQK           4       0.95000         0.331
...                        ...         ...           ...           ...
232720  2XGLdVl7lGeq8ksM6Al7jT          39       0.00384         0.687
232721  1qWZdkBl4UVPj9lK6HuuFM          38       0.03290         0.785
232722  2ziWXUmQLrXTiYjCg2fZ2t          47       0.90100         0.517
232723  6EFsue2YbIG4Qkq8Zr9Rir          44       0.26200         0.745
232724  34XO9RwPMKjbvRry54QzWn          35       0.09730         0.758

        duration_ms  energy  instrumentalness key  liveness  loudness   mode  \
0             99373   0.910          0.000000  C#    0.3460    -1.828  Major
1            137373   0.737          0.000000  F#    0.1510    -5.559  Minor
2            170267   0.131          0.000000   C    0.1030   -13.879  Minor
3            152427   0.326          0.000000  C#    0.0985   -12.178  Major
4             82625   0.225          0.123000   F    0.2020   -21.150  Major
...             ...     ...               ...  ..       ...       ...    ...
232720       326240   0.714          0.544000   D    0.0845   -10.626  Major
232721       282447   0.683          0.000880   E    0.2370    -6.944  Minor
232722       166960   0.419          0.000000   D    0.0945    -8.282  Major
232723       222442   0.704          0.000000   A    0.3330    -7.137  Major
232724       323027   0.470          0.000049  G#    0.0836    -6.708  Minor

        speechiness    tempo time_signature  valence
0            0.0525  166.969            4/4    0.814
1            0.0868  174.003            4/4    0.816
2            0.0362   99.488            5/4    0.368
3            0.0395  171.758            4/4    0.227
4            0.0456  140.576            4/4    0.390
...             ...      ...            ...      ...
232720       0.0316  115.542            4/4    0.962
232721       0.0337  113.830            4/4    0.969
232722       0.1480   84.135            4/4    0.813
232723       0.1460  100.031            4/4    0.489
232724       0.0287  113.897            4/4    0.479

[232725 rows x 18 columns]>